# modgodb database connection config (server only)
[Server.MongoDB]
DBURL = "127.0.0.1:27017"
DBName = "testdb"
UserName = "tester"
Password = "test123456"

# bridge API service (server only)
[Server.APIServer]
# listen port
Port = 12345
# CORS config
AllowedOrigins = ["*"]
# Maximum number of requests to limit per second
MaxRequestsLimit = 100

[Extra]
MustRegisterAccount = true

[BlockChain]
RPC = [
	"43114,https://api.avax.network/ext/bc/C/rpc", #avax
]

