# modgodb database connection config (server only)
[Server.MongoDB]
DBURL = "localhost:27017"
DBName = "testdb"
UserName = "tester"
Password = "test123456"

# bridge API service (server only)
[Server.APIServer]
# listen port
Port = 11556
# CORS config
AllowedOrigins = ["*"]
# Maximum number of requests to limit per second
MaxRequestsLimit = 100

[Extra]
MustRegisterAccount = true

[BlockChain]
RPC = [
	"eth,http://81.69.176.223:20812",
	"bsc,http://101.32.97.27:40290",
	"matic,http://49.235.123.22:21311",
	"ftm,http://81.69.176.223:21218",
	"fsn,http://49.235.123.22:19515",
	"ht,https://http-mainnet.hecochain.com",
	"xdai,http://49.235.123.22:21312",
	"avax,https://api.avax.network/ext/bc/C/rpc",
	"okex,https://exchainrpc.okex.org/",
	#"HMY,https://api.harmony.one",
	"harmony,https://api.s0.t.hmny.io",
	#"arb,https://arb-mainnet.g.alchemy.com/v2/H2zmJW4p_4BAw3wdvYWQnx7FI956a3ph",
	"arb,https://rpc.ankr.com/arbitrum",
	"kcs,https://rpc-mainnet.kcc.network",
	"moon,http://119.28.60.145:9955",
	"iotex,https://babel-api.mainnet.iotex.io",
	#"shiden,https://shiden.api.onfinality.io/rpc?apikey=d5da52f9-c548-4d48-8a7b-2ebb4d5d8959",
	#"shiden,https://shiden.api.onfinality.io/rpc?apikey=ed8d092a-ccfc-4ce7-bb31-ae28bd6556da",
	"shiden,https://shiden.api.onfinality.io/rpc?apikey=8509acce-2f4a-417b-a41f-b4e7bfba2bf7",
	"celo,https://forno.celo.org",
	"cro,http://124.156.136.62:25545",
	"tlos,https://rpc1.eu.telos.net/evm",
	"fuse,https://rpc.fuse.io",
	"syscoin,https://rpc.syscoin.org",
	"aurora,http://124.156.136.62:8545"

	#"BTC,http://172.26.142.156:3003",
	#"LTC,http://172.26.142.147:4334",
	#"BLOCK,https://plugin-api.core.cloudchainsinc.com" # do not modify
	#"COLX,https://electrs.colossusxt.io",
	#"OETH,https://mainnet.boba.network",
	#"TERRA,https://fcd.terra.dev/",
	#"BOBA,https://mainnet.boba.network",
]

