# risk control config
InitialDiffValue = 50.0
MaxAuditBalanceDiffValue = 100.0
MaxAuditSupplyDiffValue = 100.0
MinWithdrawReserve = 10000.0

[Email]
Server = "smtp.gmail.com"
Port = 25
From = "from@gmail.com"
FromName = "Risk Control"
Password = "***"
To = ["to1@gmail.com", "to2@gmail.com"]
Cc = ["cc1@gmail.com", "cc2@gmail.com"]

# source chain config
[SrcChain]
BlockChain = "Ethereum"
NetID = "Rinkeby"

# source token config
[SrcToken]
ID = "ERC20"
Name = "USDTERC20"
Symbol = "USDT"
Decimals = 6
Description = "ERC20 USDT"
ContractAddress = "0xb09bad01684f6d47fc7dc9591889cc77eaed8d22"
DepositAddress = "0x1249E24A077A1d95254DB00ba406100fBca8003F"
DcrmAddress = "0xb09bad01684f6d47fc7dc9591889cc77eaed8d22"

# source blockchain gateway config
[SrcGateway]
APIAddress = ["http://5.189.139.168:8018"]

# dest chain config
[DestChain]
BlockChain = "Fusion"
NetID = "Testnet"

# dest token config
[DestToken]
ID = "mUSDT"
Name = "SMPC ERC20 USDT"
Symbol = "mUSDT"
Decimals = 6
Description = "cross chain bridge USDT with mUSDT"
ContractAddress = "0x13edb3a93a985d5db4b4965d38c446ed7a931c53"
DcrmAddress = "0x826197183eB1a7D71DB073216ce157886680B094"

# dest blockchain gateway config
[DestGateway]
APIAddress = ["https://testnet.fsn.dev/api"]
